version: '3.9'

services:
  db-rifa:
    image: mysql:8.3.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web-rifa:
    image: node:18-alpine
    working_dir: /app
    command: "npm run dev"
    volumes:
      - ./rifa:/app
    ports:
      - 3000:3000
    depends_on:
      - db-rifa
  api-rifa:
    image: api_rifa
    build: ./api_rifa
    working_dir: /var/www/
    volumes:
      - ./api_rifa:/var/www/
      - ./api_rifa/public/:/var/www/html/
    ports:
      - 8200:80
    depends_on:
      - db-rifa